// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"time"
)

type Account struct {
	ID        int64     `json:"id"`
	Owner     string    `json:"owner"`
	Currency  string    `json:"currency"`
	Balance   int64     `json:"balance"`
	CreatedAt time.Time `json:"createdAt"`
}

type Entry struct {
	ID        int64     `json:"id"`
	AccountID int64     `json:"accountId"`
	Amount    int64     `json:"amount"`
	CreatedAt time.Time `json:"createdAt"`
}

type Transfer struct {
	ID            int64     `json:"id"`
	FromAccountID int64     `json:"fromAccountId"`
	ToAccountID   int64     `json:"toAccountId"`
	Amount        int64     `json:"amount"`
	CreatedAt     time.Time `json:"createdAt"`
}
